# Generated by Django 5.2.3 on 2025-08-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderpolicy_privacypolicy_shippingstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shipping/'),
        ),
    ]
