# Generated by Django 5.2.3 on 2025-08-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shippingstep_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '利用規約',
                'verbose_name_plural': '利用規約',
            },
        ),
        migrations.AlterModelOptions(
            name='orderpolicy',
            options={'verbose_name': '特定商取引法に基づく表記', 'verbose_name_plural': '特定商取引法に基づく表記'},
        ),
        migrations.RemoveField(
            model_name='orderpolicy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orderpolicy',
            name='no',
        ),
        migrations.RemoveField(
            model_name='orderpolicy',
            name='title',
        ),
        migrations.AddField(
            model_name='orderpolicy',
            name='address',
            field=models.CharField(default='Nicaragua', max_length=300, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='orderpolicy',
            name='company_name',
            field=models.CharField(default='KiMame', max_length=200, verbose_name='販売業者'),
        ),
        migrations.AddField(
            model_name='orderpolicy',
            name='delivery_time',
            field=models.CharField(blank=True, default='未設定', max_length=200, verbose_name='引渡し時期'),
        ),
        migrations.AddField(
            model_name='orderpolicy',
            name='payment_method',
            field=models.CharField(blank=True, default='未設定', max_length=200, verbose_name='支払方法'),
        ),
        migrations.AddField(
            model_name='orderpolicy',
            name='phone',
            field=models.CharField(default='未設定', max_length=50, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='orderpolicy',
            name='return_policy',
            field=models.TextField(blank=True, default='未設定', verbose_name='返品・交換・キャンセルについて'),
        ),
        migrations.AddField(
            model_name='orderpolicy',
            name='shipping_fee',
            field=models.CharField(blank=True, default='未設定', max_length=300, verbose_name='商品代金以外の必要料金'),
        ),
        migrations.AlterField(
            model_name='orderpolicy',
            name='email',
            field=models.EmailField(default='未設定', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='orderpolicy',
            name='manager',
            field=models.CharField(default='未設定', max_length=100, verbose_name='運営責任者'),
        ),
    ]
