# Generated by Django 5.2.3 on 2025-08-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_termsofservice_alter_orderpolicy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='manager',
        ),
    ]
