# Generated by Django 5.2.3 on 2025-08-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_privacypolicy_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpolicy',
            name='delivery_cost',
            field=models.CharField(blank=True, default='未設定', max_length=200, verbose_name='送料について'),
        ),
        migrations.AlterField(
            model_name='orderpolicy',
            name='delivery_time',
            field=models.CharField(blank=True, default='未設定', max_length=200, verbose_name='引渡し時期ついて'),
        ),
        migrations.AlterField(
            model_name='orderpolicy',
            name='payment_method',
            field=models.CharField(blank=True, default='未設定', max_length=200, verbose_name='支払方法に'),
        ),
    ]
