# Generated by Django 5.2.3 on 2025-08-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderpolicy_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
    ]
