# Generated by Django 5.2.3 on 2025-08-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companyinfo_favicon_companyinfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
