# Generated by Django 5.2.3 on 2025-09-16 00:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companyinfo_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': '会社概要', 'verbose_name_plural': '会社概要'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'プライバシーポリシー', 'verbose_name_plural': 'プライバシーポリシー'},
        ),
        migrations.AlterModelOptions(
            name='shippingstep',
            options={'verbose_name': '送付', 'verbose_name_plural': '送付'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='map',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='title',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='shippingstep',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
