# Generated by Django 5.2.3 on 2026-01-15 23:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='ogp_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='ogp_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ogp_image'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='ogp_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
