# Generated by Django 5.2.3 on 2026-02-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_companyinfo_ogp_description_companyinfo_ogp_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'アプリ説明',
                'verbose_name_plural': 'アプリ説明',
                'ordering': ['no'],
            },
        ),
    ]
