# Generated by Django 5.2.3 on 2026-02-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_apppolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppolicy',
            options={'ordering': ['no'], 'verbose_name': 'アプリ規約', 'verbose_name_plural': 'アプリ規約'},
        ),
        migrations.AlterField(
            model_name='orderpolicy',
            name='phone',
            field=models.CharField(blank=True, default='未設定', max_length=50, verbose_name='電話番号'),
        ),
    ]
