# Generated by Django 5.2.3 on 2026-09-18 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_apppolicy_options_alter_orderpolicy_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("contact", "お問い合わせ"), ("estimate", "お見積り")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("product", models.CharField(blank=True, max_length=100)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("prefecture", models.CharField(blank=True, max_length=10)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "お問い合わせ",
                "verbose_name_plural": "お問い合わせ",
                "ordering": ["-created_at"],
            },
        ),
    ]
