# Generated by Django 5.2.3 on 2026-10-01 07:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_inquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyChooseUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.PositiveIntegerField(default=1)),
                (
                    "title",
                    models.CharField(
                        help_text="例: 現地農家との直接取引",
                        max_length=100,
                        verbose_name="見出し",
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        help_text="選ばれる理由をストーリー形式で記述",
                        verbose_name="ストーリー本文",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "選ばれる理由",
                "verbose_name_plural": "選ばれる理由",
                "ordering": ["no"],
            },
        ),
        migrations.AlterModelOptions(
            name="shippingstep",
            options={
                "ordering": ["no"],
                "verbose_name": "送付",
                "verbose_name_plural": "送付",
            },
        ),
        migrations.AddField(
            model_name="shippingstep",
            name="detail",
            field=models.TextField(
                blank=True,
                help_text="もう少し詳しい説明(任意、一覧には小さめに表示)",
                verbose_name="補足説明",
            ),
        ),
        migrations.AddField(
            model_name="shippingstep",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="例: 約3〜5営業日",
                max_length=100,
                verbose_name="目安期間",
            ),
        ),
    ]
