# Generated by Django 5.2.3 on 2026-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_whychooseus_alter_shippingstep_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.PositiveIntegerField(default=1, verbose_name="並び順")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("product", "商品について"),
                            ("order", "ご注文・お支払い"),
                            ("shipping", "配送について"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="質問")),
                (
                    "answer",
                    models.TextField(
                        help_text="改行はそのまま反映されます", verbose_name="回答"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="公開"),
                ),
                (
                    "show_on_top",
                    models.BooleanField(
                        default=False,
                        help_text="トップページのFAQ欄に表示します(最大6件)",
                        verbose_name="トップページに表示",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "よくある質問",
                "verbose_name_plural": "よくある質問",
                "ordering": ["no", "id"],
            },
        ),
    ]
