# Generated by Django 5.2.3 on 2026-10-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_faq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="admin_note",
            field=models.TextField(
                blank=True, db_default="", default="", verbose_name="社内メモ"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "未対応"),
                    ("replied", "返信済み"),
                    ("closed", "完了"),
                ],
                db_default="new",
                default="new",
                max_length=20,
                verbose_name="対応状況",
            ),
        ),
        migrations.CreateModel(
            name="InquiryReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="件名")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="送信日時"),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.inquiry",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "返信",
                "verbose_name_plural": "返信履歴",
                "ordering": ["sent_at"],
            },
        ),
    ]
