# Generated by Django 5.2.3 on 2026-10-03 06:13

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_inquiry_status_reply"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingstep",
            options={
                "ordering": ["no"],
                "verbose_name": "お届けまでの流れ",
                "verbose_name_plural": "お届けまでの流れ",
            },
        ),
        migrations.AlterField(
            model_name="apppolicy",
            name="content",
            field=models.TextField(blank=True, verbose_name="本文"),
        ),
        migrations.AlterField(
            model_name="apppolicy",
            name="no",
            field=models.PositiveIntegerField(default=1, verbose_name="番号"),
        ),
        migrations.AlterField(
            model_name="apppolicy",
            name="title",
            field=models.CharField(max_length=200, verbose_name="見出し"),
        ),
        migrations.AlterField(
            model_name="apppolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="address",
            field=models.CharField(max_length=200, verbose_name="住所"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="description",
            field=models.TextField(blank=True, verbose_name="紹介文"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="メールアドレス"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="favicon",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ファビコン(アイコン)",
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="ロゴ"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="map",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="産地マップ画像"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="name",
            field=models.CharField(max_length=100, verbose_name="会社名"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="ogp_description",
            field=models.TextField(blank=True, verbose_name="OGP説明文"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="ogp_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="OGP画像(SNS共有用)"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="ogp_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="OGPタイトル"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="phone",
            field=models.CharField(max_length=50, verbose_name="電話番号"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="title",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="ロゴ文字画像"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="受付日時"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="メールアドレス"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="kind",
            field=models.CharField(
                choices=[("contact", "お問い合わせ"), ("estimate", "お見積り")],
                max_length=20,
                verbose_name="種類",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="message",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="name",
            field=models.CharField(max_length=100, verbose_name="お名前"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="prefecture",
            field=models.CharField(blank=True, max_length=10, verbose_name="都道府県"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="product",
            field=models.CharField(blank=True, max_length=100, verbose_name="商品名"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="予定数量"
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="会員",
            ),
        ),
        migrations.AlterField(
            model_name="inquiryreply",
            name="inquiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="core.inquiry",
                verbose_name="お問い合わせ",
            ),
        ),
        migrations.AlterField(
            model_name="inquiryreply",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="送信者",
            ),
        ),
        migrations.AlterField(
            model_name="orderpolicy",
            name="delivery_time",
            field=models.CharField(
                blank=True,
                default="未設定",
                max_length=200,
                verbose_name="引渡し時期について",
            ),
        ),
        migrations.AlterField(
            model_name="orderpolicy",
            name="payment_method",
            field=models.CharField(
                blank=True, default="未設定", max_length=200, verbose_name="支払方法"
            ),
        ),
        migrations.AlterField(
            model_name="orderpolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="description",
            field=models.TextField(blank=True, verbose_name="本文"),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="no",
            field=models.PositiveIntegerField(default=1, verbose_name="番号"),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="title",
            field=models.CharField(max_length=100, verbose_name="見出し"),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="shippingstep",
            name="description",
            field=models.TextField(blank=True, verbose_name="説明"),
        ),
        migrations.AlterField(
            model_name="shippingstep",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="画像"
            ),
        ),
        migrations.AlterField(
            model_name="shippingstep",
            name="no",
            field=models.PositiveIntegerField(default=1, verbose_name="番号"),
        ),
        migrations.AlterField(
            model_name="shippingstep",
            name="title",
            field=models.CharField(max_length=100, verbose_name="見出し"),
        ),
        migrations.AlterField(
            model_name="shippingstep",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="content",
            field=models.TextField(blank=True, verbose_name="本文"),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="no",
            field=models.PositiveIntegerField(default=1, verbose_name="番号"),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="title",
            field=models.CharField(max_length=100, verbose_name="見出し"),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="whychooseus",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="画像"
            ),
        ),
        migrations.AlterField(
            model_name="whychooseus",
            name="no",
            field=models.PositiveIntegerField(default=1, verbose_name="番号"),
        ),
        migrations.AlterField(
            model_name="whychooseus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
