# Generated by Django 5.2.3 on 2026-10-03 19:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_verbose_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="about_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="会社紹介の写真"
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="hero_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="トップ画像(ヒーロー背景)",
            ),
        ),
    ]
