# Generated by Django 5.2.3 on 2026-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=220, unique=True
            ),
        ),
    ]
