# Generated by Django 5.2.3 on 2025-08-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_logo_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
