# Generated by Django 5.2.3 on 2026-09-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_product_product_type_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="産地マップに表示する緯度(例: 12.865416)。Googleマップで場所を右クリック→座標をコピーして入力",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="産地マップに表示する経度(例: -85.207229)",
                max_digits=9,
                null=True,
            ),
        ),
    ]
