# Generated by Django 5.2.3 on 2026-09-17 09:29
# Manually reordered so existing Product.price/stock data is copied into a
# 1kg ProductVariant BEFORE those columns are dropped.

import django.db.models.deletion
from django.db import migrations, models


def copy_price_to_1kg_variant(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    ProductVariant = apps.get_model("shop", "ProductVariant")
    for product in Product.objects.all():
        ProductVariant.objects.create(
            product=product,
            weight_kg=1,
            price=product.price,
            stock=product.stock,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_latitude_product_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="weight_kg",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2, help_text="例: 1, 5, 10, 30", max_digits=6
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="この重量での販売価格(円)",
                        max_digits=8,
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "ordering": ["weight_kg"],
                "unique_together": {("product", "weight_kg")},
            },
        ),
        migrations.RunPython(copy_price_to_1kg_variant, noop_reverse),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="shop.productvariant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.productvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "variant")},
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
    ]
