# Generated by Django 5.2.3 on 2026-10-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_remove_product_price_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "受注",
                "verbose_name_plural": "受注",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="admin_note",
            field=models.TextField(
                blank=True,
                help_text="お客様には表示されません",
                verbose_name="社内メモ",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="発送日時"),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="追跡番号"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "支払い待ち"),
                    ("paid", "支払い完了"),
                    ("preparing", "発送準備中"),
                    ("failed", "決済失敗"),
                    ("fulfilled", "発送済み"),
                    ("canceled", "キャンセル"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
