# Generated by Django 5.2.3 on 2026-10-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_order_options_order_admin_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="admin_note",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="お客様には表示されません",
                verbose_name="社内メモ",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=100,
                verbose_name="追跡番号",
            ),
        ),
    ]
