# Generated by Django 5.2.3 on 2026-10-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_order_text_db_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="DHLの送り状番号(Waybill No.)。入力するとお客様の注文ページに追跡リンクが表示されます",
                max_length=100,
                verbose_name="追跡番号(DHL)",
            ),
        ),
    ]
