# Generated by Django 5.2.3 on 2026-10-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_tracking_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="notes",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="送料・関税など購入前に知っておいてほしい注意書き。商品ページで紹介文とは別枠に表示されます",
                verbose_name="ご購入時の注意",
            ),
        ),
    ]
