# Generated by Django 5.2.3 on 2026-10-03 06:13

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_product_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "住所", "verbose_name_plural": "住所"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "注文商品", "verbose_name_plural": "注文商品"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "商品", "verbose_name_plural": "商品"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "ギャラリー画像",
                "verbose_name_plural": "ギャラリー画像",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ["weight_kg"],
                "verbose_name": "重量・価格",
                "verbose_name_plural": "重量・価格",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line1",
            field=models.CharField(max_length=200, verbose_name="番地"),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line2",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="建物名など"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100, verbose_name="市区町村"),
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="お名前"),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=True, verbose_name="いつもの住所"),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="電話番号"),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="郵便番号"),
        ),
        migrations.AlterField(
            model_name="address",
            name="prefecture",
            field=models.CharField(max_length=10, verbose_name="都道府県"),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="会員",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="contact_email",
            field=models.EmailField(max_length=254, verbose_name="メールアドレス"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="注文日時"),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支払日時"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address_line1",
            field=models.CharField(max_length=200, verbose_name="番地"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address_line2",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="建物名など"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(max_length=100, verbose_name="市区町村"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="送料"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_name",
            field=models.CharField(max_length=100, verbose_name="お名前"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(max_length=20, verbose_name="電話番号"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_postal_code",
            field=models.CharField(max_length=10, verbose_name="郵便番号"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_prefecture",
            field=models.CharField(max_length=10, verbose_name="都道府県"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "支払い待ち"),
                    ("paid", "支払い完了"),
                    ("preparing", "発送準備中"),
                    ("failed", "決済失敗"),
                    ("fulfilled", "発送済み"),
                    ("canceled", "キャンセル"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状態",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=200,
                verbose_name="Stripe決済セッションID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="Stripe支払いID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="小計"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="合計"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="会員",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shop.order",
                verbose_name="受注",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=200, verbose_name="商品名"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="単価"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.productvariant",
                verbose_name="重量・価格",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=6, verbose_name="重量(kg)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="紹介文"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="トップ画像"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="産地マップに表示する緯度(例: 12.865416)。Googleマップで場所を右クリック→座標をコピーして入力",
                max_digits=9,
                null=True,
                verbose_name="緯度",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="ロゴ"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="産地マップに表示する経度(例: -85.207229)",
                max_digits=9,
                null=True,
                verbose_name="経度",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="map",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="地図画像"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="商品名"),
        ),
        migrations.AlterField(
            model_name="product",
            name="no",
            field=models.PositiveIntegerField(default=1, verbose_name="表示順"),
        ),
        migrations.AlterField(
            model_name="product",
            name="origin",
            field=models.CharField(
                help_text="例: ニカラグア、エチオピアなど",
                max_length=100,
                verbose_name="産地",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("coffee", "コーヒー"), ("cacao", "カカオ")],
                default="coffee",
                max_length=20,
                verbose_name="種類",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="roast_level",
            field=models.CharField(
                blank=True,
                help_text="例: 生豆、ライトロースト",
                max_length=50,
                verbose_name="焙煎度",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="キャッチコピー"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="画像"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="並び順"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="この重量での販売価格(円)",
                max_digits=8,
                verbose_name="価格(円)",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="shop.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="在庫"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="例: 1, 5, 10, 30",
                max_digits=6,
                verbose_name="重量(kg)",
            ),
        ),
    ]
